### PR TITLE
Remove unnecessary files from docs and disable the translation bot in the repo

### PR DESCRIPTION
**Pull request by r0qs**
The documentation repository does not need CI configs, so I'm removing it since it will always fail.

### CODE REVIEW

**Comment by cameel** [comment]
I'd leave `.gitigore` in. A lot of stuff from it could be removed but even in the default form from our repo it has some use here.

**Comment by cameel** [comment]
Oh, also, the repo is actually missing one file. It not have `CMakeLists.txt`, so Sphinx build will fail [trying to extract version from it](https://github.com/solidity-docs/ru-russian/blob/develop/docs/conf.py#L73-L74).

**Comment by r0qs** [comment]
> one

Ops, I will add it and restore the .gitignore.

**Comment by r0qs** [comment]
> Oh, also, the repo is actually missing one file. It not have `CMakeLists.txt`, so Sphinx build will fail [trying to extract version from it](https://github.com/solidity-docs/ru-russian/blob/develop/docs/conf.py#L73-L74).

Hum...but do you know in which version are they translating? It seems that changes in their develop branch were pushed directly and not via the bot's PR, and I couldn't really find when the `CMakeLists.txt` was removed.

**Comment by r0qs** [comment]
Hi @VSGic and @olganicegirl which Solidity version are you currently translating?

**Comment by cameel** [comment]
Somewhere between 0.8.13 and 0.8.14. This commit removed the file: 933f373eb4c5f3a7a02f86235686c15a83614d63.

> Hi @VSGic and @olganicegirl which Solidity version are you currently translating?

They're basically translating that intermediate point between versions.

@VSGic, @olganicegirl my suggestion would be to disable the bot for the time being and close the pending sync PRs that the bot created up to now. We could do that for you and submit a sync PR specifically for 0.8.14 so that you can target exactly that version. When you're done, you'd tag it and we'd link to it from them main docs. We'd then give you a sync PR for 0.8.15 and so on. Eventually this will be the default workflow and automated.

Another option would be to jump directly to the latest version without translating and tagging the intermediate revisions. We'd then give you a sync PR to 0.8.18 (or 0.8.19, since we're releasing that soon).

In any case, it's also fine to just finish translating whatever you have in the repo now and only go back to the topic once you're ready to tag and release it.

**Comment by r0qs** [comment]
Thanks @cameel  I restored the `CMakeLists.txt` and added the translation bot config with the sync-pr disabled.

**Pull request merged**
